services:
  mysql:
    image: mysql:8
    container_name: my-finance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance-db
      MYSQL_USER: finance-user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    # command: --initialize-insecure --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/radaskey/mysql_data:/var/lib/mysql
volumes:
  mysql_data:
